#!/bin/bash
# example command is ./quickconverter.py -i ../../derivatives/topup_python/per-slice_contrast-matched/sub-4522954/ses-20240820110756/run-1020_desc-AX_DWI_4echo_IBD_RESEARCH/sub-4522954_ses-20240820110756_run-1020_desc-AX_DWI_4echo_IBD_RESEARCH_bv-1_sv-12_merged_per-slice_contrast-matched.nii -o ./temp_input/test_slice_bv-1_sv-12.nii.gz -s
# we want to go through each slice and bvals and put them in the output directory
subject="sub-4522954"
session="ses-20240820110756"
run="run-1020"
input_dir="../../derivatives/topup_python/per-slice_contrast-matched/${subject}/${session}/${run}_desc-AX_DWI_4echo_IBD_RESEARCH"
output_dir="./temp_input"
# input_files=$(fdfind -d 1 -e nii.gz "sub-${subject}_${session}_${run}_desc-AX_DWI_4echo_IBD_RESEARCH_bv-1_sv-[0-9]*_merged_per-slice_contrast-matched.nii" ${input_dir} | sort)
# input_files=$(ls ${input_dir}/*bv-1_*_merged_per-slice_contrast-matched.nii | sort)
# echo $input_files
bvol=50
for f in ${input_dir}/*bv-${bvol}_*_merged_per-slice_contrast-matched.nii; do
	echo $f
	slice=$(basename $f | sed -n 's/.*_sv-\([0-9]*\)_merged_per-slice_contrast-matched.nii/\1/p')
	output_file="${output_dir}/${subject}_${session}_${run}_desc-cm_fdnetinput_bv-${bvol}_sv-${slice}.nii.gz"
	echo $output_file
	./quickconverter.py -i $f -o $output_file -s
done
# code_path="/fileserver/external/body/liam/distortion_dev/nov24_grant/code/tolganet/network"
# cd $code_path
# python fdnet11.py --custompath ../temp_input/ --customshape 144 168 --weights ../../fdnet_weights_42_subjects --savedir ../temp_output --legacy --batch_size 1 --dontskip
# cd -
